export const Routes = {
    WEB: {
        HOME: '/',
        LOGIN: '/login',
        SIGNUP: '/signup',
        PRODUCTS: '/products',
        VIEW_CART: '/view_cart',
        CHECKOUT: '/checkout',
        PAYMENT: '/payment',
        PAYMENT_DONE: '/payment_done',
        CONTACT_US: '/contact_us',
        ACCOUNT_CREATED: '/account_created',
        HOME_TITLE: 'Automation Exercise',
        TEST_CASES: '/test_cases',
    },
    API: {
        PRODUCTS_LIST: '/api/productsList',
        BRANDS_LIST: '/api/brandsList',
        SEARCH_PRODUCT: '/api/searchProduct',
        VERIFY_LOGIN: '/api/verifyLogin',
        CREATE_ACCOUNT: '/api/createAccount',
        DELETE_ACCOUNT: '/api/deleteAccount',
        UPDATE_ACCOUNT: '/api/updateAccount',
        GET_USER_DETAIL_BY_EMAIL: '/api/getUserDetailByEmail',
    },
} as const;